name: info_carousel
description: Tiki info carousel.
version: 0.0.7
homepage: https://mytiki.com
repository: https://github.com/tiki/info_carousel
issue_tracker: https://github.com/tiki/info_carousel/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  share_plus: ^4.0.9
  provider: ^6.0.3
  url_launcher: ^6.1.3
  tiki_style: ^0.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0