name: info_carousel
description: A new Flutter project.
version: 0.0.4
repository: https://github.com/tiki/info_carousel
publish_to: none  # this package is in active development.

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  logging: ^1.0.2
  path_provider: ^2.0.9
  permission_handler: ^8.3.0
  share_plus: ^3.1.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  style:
    git:
      url: https://github.com/tiki/style
      ref: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0