name: info_carousel
description: Tiki info carousel.
version: 0.0.4
homepage: https://mytiki.com
repository: https://github.com/tiki/info_carousel
issue_tracker: https://github.com/tiki/info_carousel/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.1.1
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  share_plus: ^3.1.0
  provider: ^6.0.2
  url_launcher: ^6.1.0
  tiki_style: ^0.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0